"""report_jules_usage.py — Jules 消費の日次集計 (#1200 dashboard)

毎日 16-jules-daily-report.yml から実行される。`gh` CLI 経由で:
  - app/google-labs-jules[bot] が当日起票した PR 件数 (= 実際の Jules session 数)
  - 03/12/14 workflow の run 件数と conclusion 内訳

を取得し、markdown を stdout に出力する。caller は `gh issue comment` で
Issue #1200 に貼り付ける。

使い方:
    python scripts/report_jules_usage.py                # 今日 (UTC)
    python scripts/report_jules_usage.py --date 2026-05-31

設計判断:
  - cap check は 03-invoke-jules と同じ author:app/google-labs-jules を使う
    (workflow_runs ベースだと 100 件超で paging が必要なため)
  - 14-brand-narrative の Jules PR は author が違う可能性ある → 02-publish
    が触らないため当日 PR 集計には混ざらない (将来 narrative も AUTO_CREATE_PR
    で google-labs-jules 起票なら自然と含まれる)
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import subprocess
import sys

REPO = "omochairo/amazon"
DAILY_CAP = 30  # 03-invoke-jules.yml の DAILY_CAP と一致させる

# workflow id は gh api repos/.../actions/workflows で取得した固定値。
WORKFLOWS = [
    ("03-invoke-jules (new articles)", 274335114),
    ("12-rewrite-idle-fill (rewrites)", 283624256),
    ("14-brand-narrative (brand hubs)", 285963710),
]


def _gh(args: list[str]) -> str:
    r = subprocess.run(["gh"] + args, capture_output=True, text=True, check=False)
    if r.returncode != 0:
        sys.stderr.write(f"gh {' '.join(args)} failed: {r.stderr}\n")
        return ""
    return r.stdout


def jules_prs_today(date: str) -> list[dict]:
    out = _gh([
        "pr", "list", "-R", REPO, "--state", "all",
        "--search", f"author:app/google-labs-jules created:{date}",
        "--json", "number,state,title", "--limit", "200",
    ])
    try:
        return json.loads(out) if out else []
    except json.JSONDecodeError:
        return []


def workflow_runs_today(wf_id: int, date: str) -> list[dict]:
    out = _gh([
        "api",
        f"repos/{REPO}/actions/workflows/{wf_id}/runs?created={date}&per_page=100",
        "--jq", "[.workflow_runs[] | {conclusion, event}]",
    ])
    try:
        return json.loads(out) if out else []
    except json.JSONDecodeError:
        return []


def _status_emoji(pr_count: int) -> str:
    if pr_count >= DAILY_CAP:
        return "🔴 CAP HIT"
    if pr_count >= int(DAILY_CAP * 0.8):
        return "🟡 Warning (cap 接近)"
    return "🟢 OK"


def render(date: str) -> str:
    prs = jules_prs_today(date)
    pr_count = len(prs)
    merged = sum(1 for p in prs if p.get("state") == "MERGED")
    open_count = sum(1 for p in prs if p.get("state") == "OPEN")
    closed = sum(1 for p in prs if p.get("state") == "CLOSED")
    status = _status_emoji(pr_count)

    lines = []
    lines.append(f"## Jules usage — {date} UTC")
    lines.append("")
    lines.append(f"**Jules PRs: {pr_count} / cap {DAILY_CAP}** &nbsp; {status}")
    lines.append("")
    lines.append(f"- merged: {merged}")
    lines.append(f"- open: {open_count}")
    lines.append(f"- closed (not merged): {closed}")
    lines.append("")
    lines.append("### Workflow runs")
    lines.append("")
    lines.append("| workflow | total | success | failure | cancelled | other |")
    lines.append("|---|---:|---:|---:|---:|---:|")
    for name, wf_id in WORKFLOWS:
        runs = workflow_runs_today(wf_id, date)
        total = len(runs)
        success = sum(1 for r in runs if r.get("conclusion") == "success")
        failure = sum(1 for r in runs if r.get("conclusion") == "failure")
        cancelled = sum(1 for r in runs if r.get("conclusion") == "cancelled")
        other = total - success - failure - cancelled
        lines.append(f"| {name} | {total} | {success} | {failure} | {cancelled} | {other} |")
    lines.append("")
    lines.append("_Generated by `scripts/report_jules_usage.py` via "
                 "`16-jules-daily-report.yml`._")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--date", default=None, help="YYYY-MM-DD (UTC). Default: today.")
    args = p.parse_args()
    date = args.date or _dt.datetime.utcnow().strftime("%Y-%m-%d")
    print(render(date))
    return 0


if __name__ == "__main__":
    sys.exit(main())
